val quot : Utf8_char.t
val semicolon : Utf8_char.t
val amp : Utf8_char.t
val hash : Utf8_char.t
val lt : Utf8_char.t
val gt : Utf8_char.t
val bkslash : Utf8_char.t
val apos : Utf8_char.t
val quot : Utf8_char.t
val colon : Utf8_char.t
val eq : Utf8_char.t
val uscore : Utf8_char.t
val slash : Utf8_char.t
val ques : Utf8_char.t
val excl : Utf8_char.t
val openbr : Utf8_char.t
val closebr : Utf8_char.t
val dash : Utf8_char.t
val twodashes : string
val quesgt : string
val openbr_cdata_openbr : string

